# Generated by Django 3.2.2 on 2021-05-26 13:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('open', '0003_auto_20210526_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 26, 13, 34, 35, 234445, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='story',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 26, 13, 34, 35, 234445, tzinfo=utc)),
        ),
    ]
